(function (global) {
  var ns = global.BlockIsland = global.BlockIsland || {};

  var BASE_EAT_COST = 18;
  var BASE_SOCIALIZE_COST = 8;
  var TIP_CHANCE_BASE = 0.25;
  var TIP_CHANCE_MAX = 0.75;
  var TIP_MIN = 5;
  var TIP_MAX = 35;
  var BUSY_SEASON_TIP_MULT = 1.25;
  var SUMMER_PEOPLE_TIP_CHANCE_PER_POINT = 0.002;
  var LOCALS_TIP_CHANCE_PER_POINT = 0.001;
  var SUMMER_PEOPLE_TIP_AMOUNT_PER_POINT = 0.004;
  var LOCALS_TIP_AMOUNT_PER_POINT = 0.002;

  ns.balance = {
    BASE_EAT_COST: BASE_EAT_COST,
    BASE_SOCIALIZE_COST: BASE_SOCIALIZE_COST,
    TIP_CHANCE_BASE: TIP_CHANCE_BASE,
    TIP_CHANCE_MAX: TIP_CHANCE_MAX,
    TIP_MIN: TIP_MIN,
    TIP_MAX: TIP_MAX,
    BUSY_SEASON_TIP_MULT: BUSY_SEASON_TIP_MULT,
    SUMMER_PEOPLE_TIP_CHANCE_PER_POINT: SUMMER_PEOPLE_TIP_CHANCE_PER_POINT,
    LOCALS_TIP_CHANCE_PER_POINT: LOCALS_TIP_CHANCE_PER_POINT,
    SUMMER_PEOPLE_TIP_AMOUNT_PER_POINT: SUMMER_PEOPLE_TIP_AMOUNT_PER_POINT,
    LOCALS_TIP_AMOUNT_PER_POINT: LOCALS_TIP_AMOUNT_PER_POINT
  };
})(window);
